//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuIDE.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("QuIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        public static string AddControl {
            get {
                return ResourceManager.GetString("AddControl", resourceCulture);
            }
        }
        
        public static string AddQubit {
            get {
                return ResourceManager.GetString("AddQubit", resourceCulture);
            }
        }
        
        public static string AddRegister {
            get {
                return ResourceManager.GetString("AddRegister", resourceCulture);
            }
        }
        
        public static string AddStep {
            get {
                return ResourceManager.GetString("AddStep", resourceCulture);
            }
        }
        
        public static string Amplitude {
            get {
                return ResourceManager.GetString("Amplitude", resourceCulture);
            }
        }
        
        public static string AngleValue {
            get {
                return ResourceManager.GetString("AngleValue", resourceCulture);
            }
        }
        
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string CircuitDesigner {
            get {
                return ResourceManager.GetString("CircuitDesigner", resourceCulture);
            }
        }
        
        public static string ClearCircuit {
            get {
                return ResourceManager.GetString("ClearCircuit", resourceCulture);
            }
        }
        
        public static string Composite {
            get {
                return ResourceManager.GetString("Composite", resourceCulture);
            }
        }
        
        public static string ConsoleOutput {
            get {
                return ResourceManager.GetString("ConsoleOutput", resourceCulture);
            }
        }
        
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        public static string CPhaseShift {
            get {
                return ResourceManager.GetString("CPhaseShift", resourceCulture);
            }
        }
        
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        public static string DeleteColumn {
            get {
                return ResourceManager.GetString("DeleteColumn", resourceCulture);
            }
        }
        
        public static string DeleteQubit {
            get {
                return ResourceManager.GetString("DeleteQubit", resourceCulture);
            }
        }
        
        public static string DeleteRegister {
            get {
                return ResourceManager.GetString("DeleteRegister", resourceCulture);
            }
        }
        
        public static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        public static string DistValue {
            get {
                return ResourceManager.GetString("DistValue", resourceCulture);
            }
        }
        
        public static string DragGates {
            get {
                return ResourceManager.GetString("DragGates", resourceCulture);
            }
        }
        
        public static string EraseGate {
            get {
                return ResourceManager.GetString("EraseGate", resourceCulture);
            }
        }
        
        public static string FlipBit {
            get {
                return ResourceManager.GetString("FlipBit", resourceCulture);
            }
        }
        
        public static string GenerateCode {
            get {
                return ResourceManager.GetString("GenerateCode", resourceCulture);
            }
        }
        
        public static string GenerateFromCode {
            get {
                return ResourceManager.GetString("GenerateFromCode", resourceCulture);
            }
        }
        
        public static string Hadamard {
            get {
                return ResourceManager.GetString("Hadamard", resourceCulture);
            }
        }
        
        public static string InsertColumnLeft {
            get {
                return ResourceManager.GetString("InsertColumnLeft", resourceCulture);
            }
        }
        
        public static string InsertColumnRight {
            get {
                return ResourceManager.GetString("InsertColumnRight", resourceCulture);
            }
        }
        
        public static string InsertQubitAbove {
            get {
                return ResourceManager.GetString("InsertQubitAbove", resourceCulture);
            }
        }
        
        public static string InsertQubitBelow {
            get {
                return ResourceManager.GetString("InsertQubitBelow", resourceCulture);
            }
        }
        
        public static string InsertRegisterAbove {
            get {
                return ResourceManager.GetString("InsertRegisterAbove", resourceCulture);
            }
        }
        
        public static string InsertRegisterBelow {
            get {
                return ResourceManager.GetString("InsertRegisterBelow", resourceCulture);
            }
        }
        
        public static string InsertRowAbove {
            get {
                return ResourceManager.GetString("InsertRowAbove", resourceCulture);
            }
        }
        
        public static string InsertRowBelow {
            get {
                return ResourceManager.GetString("InsertRowBelow", resourceCulture);
            }
        }
        
        public static string InvCPhaseShift {
            get {
                return ResourceManager.GetString("InvCPhaseShift", resourceCulture);
            }
        }
        
        public static string MatrixNotUnitary {
            get {
                return ResourceManager.GetString("MatrixNotUnitary", resourceCulture);
            }
        }
        
        public static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string OperationMatrix {
            get {
                return ResourceManager.GetString("OperationMatrix", resourceCulture);
            }
        }
        
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        public static string PhaseKick {
            get {
                return ResourceManager.GetString("PhaseKick", resourceCulture);
            }
        }
        
        public static string PhaseScale {
            get {
                return ResourceManager.GetString("PhaseScale", resourceCulture);
            }
        }
        
        public static string Pi {
            get {
                return ResourceManager.GetString("Pi", resourceCulture);
            }
        }
        
        public static string Pi_2 {
            get {
                return ResourceManager.GetString("Pi_2", resourceCulture);
            }
        }
        
        public static string Pi_3 {
            get {
                return ResourceManager.GetString("Pi_3", resourceCulture);
            }
        }
        
        public static string Pi_4 {
            get {
                return ResourceManager.GetString("Pi_4", resourceCulture);
            }
        }
        
        public static string Pi_6 {
            get {
                return ResourceManager.GetString("Pi_6", resourceCulture);
            }
        }
        
        public static string Pi_8 {
            get {
                return ResourceManager.GetString("Pi_8", resourceCulture);
            }
        }
        
        public static string Pointer {
            get {
                return ResourceManager.GetString("Pointer", resourceCulture);
            }
        }
        
        public static string PrevStep {
            get {
                return ResourceManager.GetString("PrevStep", resourceCulture);
            }
        }
        
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        public static string Probability {
            get {
                return ResourceManager.GetString("Probability", resourceCulture);
            }
        }
        
        public static string ProbabilityScale {
            get {
                return ResourceManager.GetString("ProbabilityScale", resourceCulture);
            }
        }
        
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        public static string QFT {
            get {
                return ResourceManager.GetString("QFT", resourceCulture);
            }
        }
        
        public static string Qubits {
            get {
                return ResourceManager.GetString("Qubits", resourceCulture);
            }
        }
        
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        public static string RemoveQubit {
            get {
                return ResourceManager.GetString("RemoveQubit", resourceCulture);
            }
        }
        
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        public static string RotateX {
            get {
                return ResourceManager.GetString("RotateX", resourceCulture);
            }
        }
        
        public static string RotateY {
            get {
                return ResourceManager.GetString("RotateY", resourceCulture);
            }
        }
        
        public static string RotateZ {
            get {
                return ResourceManager.GetString("RotateZ", resourceCulture);
            }
        }
        
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        public static string RunInConsole {
            get {
                return ResourceManager.GetString("RunInConsole", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        public static string SelectCompositeGate {
            get {
                return ResourceManager.GetString("SelectCompositeGate", resourceCulture);
            }
        }
        
        public static string SelectMethod {
            get {
                return ResourceManager.GetString("SelectMethod", resourceCulture);
            }
        }
        
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        public static string ShowOnlyNonZero {
            get {
                return ResourceManager.GetString("ShowOnlyNonZero", resourceCulture);
            }
        }
        
        public static string SigmaX {
            get {
                return ResourceManager.GetString("SigmaX", resourceCulture);
            }
        }
        
        public static string SigmaY {
            get {
                return ResourceManager.GetString("SigmaY", resourceCulture);
            }
        }
        
        public static string SigmaZ {
            get {
                return ResourceManager.GetString("SigmaZ", resourceCulture);
            }
        }
        
        public static string SqrtX {
            get {
                return ResourceManager.GetString("SqrtX", resourceCulture);
            }
        }
        
        public static string StateAmplitude {
            get {
                return ResourceManager.GetString("StateAmplitude", resourceCulture);
            }
        }
        
        public static string StateProbability {
            get {
                return ResourceManager.GetString("StateProbability", resourceCulture);
            }
        }
        
        public static string StateQubits {
            get {
                return ResourceManager.GetString("StateQubits", resourceCulture);
            }
        }
        
        public static string StatesVisibility {
            get {
                return ResourceManager.GetString("StatesVisibility", resourceCulture);
            }
        }
        
        public static string StateValue {
            get {
                return ResourceManager.GetString("StateValue", resourceCulture);
            }
        }
        
        public static string Ungroup {
            get {
                return ResourceManager.GetString("Ungroup", resourceCulture);
            }
        }
        
        public static string Unitary {
            get {
                return ResourceManager.GetString("Unitary", resourceCulture);
            }
        }
        
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        public static string SelectedCompositeGate {
            get {
                return ResourceManager.GetString("SelectedCompositeGate", resourceCulture);
            }
        }
        
        public static string AddParam {
            get {
                return ResourceManager.GetString("AddParam", resourceCulture);
            }
        }
        
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        public static string GroupTip {
            get {
                return ResourceManager.GetString("GroupTip", resourceCulture);
            }
        }
        
        public static string UngroupTip {
            get {
                return ResourceManager.GetString("UngroupTip", resourceCulture);
            }
        }
        
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        public static string InitValue {
            get {
                return ResourceManager.GetString("InitValue", resourceCulture);
            }
        }
        
        public static string QubitsNumber {
            get {
                return ResourceManager.GetString("QubitsNumber", resourceCulture);
            }
        }
        
        public static string InitState {
            get {
                return ResourceManager.GetString("InitState", resourceCulture);
            }
        }
        
        public static string AmplitudesNormalizationCaution {
            get {
                return ResourceManager.GetString("AmplitudesNormalizationCaution", resourceCulture);
            }
        }
        
        public static string Calculator {
            get {
                return ResourceManager.GetString("Calculator", resourceCulture);
            }
        }
        
        public static string CopyResult {
            get {
                return ResourceManager.GetString("CopyResult", resourceCulture);
            }
        }
        
        public static string ShowCalculator {
            get {
                return ResourceManager.GetString("ShowCalculator", resourceCulture);
            }
        }
        
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        public static string InConsole {
            get {
                return ResourceManager.GetString("InConsole", resourceCulture);
            }
        }
        
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        public static string ToCircuit {
            get {
                return ResourceManager.GetString("ToCircuit", resourceCulture);
            }
        }
        
        public static string ToCode {
            get {
                return ResourceManager.GetString("ToCode", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string ShowAbout {
            get {
                return ResourceManager.GetString("ShowAbout", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        public static string GPLText {
            get {
                return ResourceManager.GetString("GPLText", resourceCulture);
            }
        }
        
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        public static string NoImg {
            get {
                return ResourceManager.GetString("NoImg", resourceCulture);
            }
        }
        
        public static string NoQubit {
            get {
                return ResourceManager.GetString("NoQubit", resourceCulture);
            }
        }
        
        public static string AreaTooSmall {
            get {
                return ResourceManager.GetString("AreaTooSmall", resourceCulture);
            }
        }
        
        public static string QubitEntanlged {
            get {
                return ResourceManager.GetString("QubitEntanlged", resourceCulture);
            }
        }
        
        public static string KetZero {
            get {
                return ResourceManager.GetString("KetZero", resourceCulture);
            }
        }
        
        public static string KetOne {
            get {
                return ResourceManager.GetString("KetOne", resourceCulture);
            }
        }
        
        public static string KetPlus {
            get {
                return ResourceManager.GetString("KetPlus", resourceCulture);
            }
        }
        
        public static string KetMinus {
            get {
                return ResourceManager.GetString("KetMinus", resourceCulture);
            }
        }
        
        public static string KetPositive_I {
            get {
                return ResourceManager.GetString("KetPositive_I", resourceCulture);
            }
        }
        
        public static string KetNegative_I {
            get {
                return ResourceManager.GetString("KetNegative_I", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string NoRegisterForQubitFound {
            get {
                return ResourceManager.GetString("NoRegisterForQubitFound", resourceCulture);
            }
        }
    }
}
