# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Build Linux-single-file-app
      run: dotnet publish QuIDE/QuIDE.csproj -r linux-x64 -f net8.0 -p:PublishSingleFile=true --self-contained false

    - name: Build Windows-single-file-app
      run: dotnet publish QuIDE/QuIDE.csproj -r win-x64 -f net8.0 -p:PublishSingleFile=true --self-contained false

    - name: Build macOS
      run: dotnet publish QuIDE/QuIDE.csproj -r osx-arm64
    - name: build macOS app
      run: dotnet msbuild QuIDE/QuIDE.csproj -t:BundleApp -p:Configuration=Release -p:RuntimeIdentifier=osx-arm64
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: QuIDE Linux amd64
        path: QuIDE/bin/Release/net8.0/linux-x64/publish/QuIDE

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: QuIDE Windows amd64
        path: QuIDE/bin/Release/net8.0/win-x64/publish/QuIDE.exe

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: QuIDE macOS arm64
        path: QuIDE/bin/Release/net8.0/osx-arm64/publish/QuIDE.app
